# Generated by Django 4.2.8 on 2024-01-04 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='variant_cetegory',
            new_name='variant_category',
        ),
    ]
