# Generated by Django 4.2.8 on 2024-01-06 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_variant_cetegory_variant_variant_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(help_text='Enter a number greater than zero', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(help_text='Enter a number greater than zero', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
