# Generated by Django 4.2.8 on 2024-01-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_price_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_product',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
