# Generated by Django 4.2.8 on 2024-01-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_price_alter_product_stock'),
        ('orders', '0003_remove_orderproduct_color_remove_orderproduct_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='variant',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='variant',
            field=models.ManyToManyField(blank=True, to='store.variant'),
        ),
    ]
