# Generated by Django 4.2.8 on 2024-01-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderproduct_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='tax',
            field=models.FloatField(),
        ),
    ]
