# Generated by Django 4.2.8 on 2024-01-21 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_orderproduct_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='tax',
        ),
    ]
