# Generated by Django 4.2.8 on 2024-02-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='offer_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
