# Generated by Django 4.2.8 on 2024-02-01 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orderproduct_offer_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='offer_price',
        ),
    ]
