# Generated by Django 4.2.8 on 2024-02-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_delete_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
