# Generated by Django 4.2.8 on 2024-02-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='coupon_discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product_discount',
            field=models.FloatField(default=0.0),
        ),
    ]
