# Generated by Django 4.2.8 on 2024-02-15 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_order_coupon_discount_orderproduct_coupon_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='coupon_discount',
        ),
    ]
