# Generated by Django 4.2.8 on 2024-01-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_phone_number_alter_profile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x00000193FE6A9670>', max_length=200),
        ),
    ]
