# Generated by Django 4.2.8 on 2024-01-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_accountuser_session_alter_profile_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountuser',
            name='session',
        ),
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x0000023E9EB0A670>', max_length=200),
        ),
    ]
