# Generated by Django 4.2.8 on 2024-01-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_accountuser_session_alter_profile_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='session',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000001C0B06D9670>', max_length=200),
        ),
    ]
