# Generated by Django 4.2.8 on 2024-02-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0078_remove_account_phone_number_alter_profile_uid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountUser',
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000001A666F52C10>', max_length=200),
        ),
    ]
