# Generated by Django 4.2.8 on 2024-02-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0079_delete_accountuser_account_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default='', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000001797FC38C10>', max_length=200),
        ),
    ]
