# Generated by Django 4.2.8 on 2024-01-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_variant_cetegory_variant_variant_category'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ManyToManyField(blank=True, to='store.variant'),
        ),
    ]
