# Generated by Django 4.2.8 on 2024-01-06 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Enter a number greater than zero', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
