# Generated by Django 4.2.8 on 2024-02-03 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_cart_coupon_cartitem_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='coupon',
        ),
    ]
