# Generated by Django 4.2.8 on 2024-02-04 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_coupons_remove_cart_coupon_remove_cartitem_coupon_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='Coupons',
        ),
    ]
