# Generated by Django 4.2.8 on 2024-02-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0010_delete_coupon_delete_coupons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('minimum_amount', models.IntegerField(default=10000)),
                ('discount', models.IntegerField(default=0)),
                ('is_expired', models.BooleanField(default=False)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
            ],
        ),
    ]
