# Generated by Django 4.2.8 on 2024-02-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0012_usercoupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='grand_total',
            field=models.FloatField(default=0),
        ),
    ]
