# Generated by Django 4.2.8 on 2024-02-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0013_cartitem_grand_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='grand_total',
        ),
        migrations.AddField(
            model_name='cart',
            name='grand_total',
            field=models.FloatField(default=0),
        ),
    ]
