# Generated by Django 4.2.8 on 2024-02-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0014_remove_cartitem_grand_total_cart_grand_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='grand_total',
        ),
    ]
